# Generated by Django 4.1.5 on 2023-01-09 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("occupation", models.CharField(max_length=128)),
                ("salary", models.IntegerField()),
                ("salary_claim", models.IntegerField()),
                ("is_retired", models.BooleanField(default=False)),
            ],
        ),
    ]
