# Generated by Django 4.1.5 on 2023-01-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_infos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finance",
            old_name="user_id",
            new_name="user",
        ),
    ]
