# Generated by Django 4.1.5 on 2023-01-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance_infos", "0002_rename_user_id_finance_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finance",
            old_name="user",
            new_name="user_id",
        ),
    ]
