# Generated by Django 4.1.5 on 2023-01-06 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance_infos", "0004_rename_user_id_finance_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finance_infos",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
