# Generated by Django 4.1.5 on 2023-01-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_infos", "0003_alter_heath_info_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heath_info",
            name="bmi",
            field=models.IntegerField(),
        ),
    ]
