# Generated by Django 4.1.5 on 2023-01-10 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "work",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "sleep",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "study",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "hobby",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "health",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
