# Generated by Django 4.1.5 on 2023-01-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_quotas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquota",
            name="type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("total", "Default")],
                default="total",
                max_length=32,
            ),
        ),
    ]
