# Generated by Django 4.1.5 on 2023-01-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_quotas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyquota",
            name="user",
        ),
    ]
