# Generated by Django 4.1.5 on 2023-01-12 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_quotas", "0002_alter_dailyquota_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyquota",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_quota",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("total", "Default")],
                default="total",
                max_length=32,
            ),
        ),
    ]
