# Generated by Django 4.1.5 on 2023-01-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_quotas",
            "0003_alter_dailyquota_health_alter_dailyquota_hobby_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquota",
            name="health",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="hobby",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="sleep",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="study",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="work",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
