# Generated by Django 4.1.5 on 2023-01-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_quotas",
            "0005_alter_dailyquota_health_alter_dailyquota_hobby_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquota",
            name="health",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="hobby",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="sleep",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="study",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="work",
            field=models.FloatField(default=0),
        ),
    ]
