# Generated by Django 4.1.5 on 2023-01-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_quotas",
            "0006_alter_dailyquota_health_alter_dailyquota_hobby_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyquota",
            name="type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("total", "Default")],
                default="total",
                max_length=32,
            ),
        ),
    ]
