# Generated by Django 4.1.5 on 2023-01-11 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Academic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "educational_level",
                    models.CharField(
                        choices=[
                            ("Early childhood education", "Isced0"),
                            ("Primary Education", "Isced1"),
                            ("Lower Secondary Education", "Isced2"),
                            ("Upper Secondary Education", "Isced3"),
                            ("Post-Secondary non-Tertiary Education", "Isced4"),
                            ("Short-cycle tertiary education", "Isced5"),
                            (
                                "Bachelors degree or equivalent education level",
                                "Isced6",
                            ),
                            ("Masters degree or equivalent education level", "Isced7"),
                            ("Doctoral degree or equivalent education level", "Isced8"),
                            ("Not Informed", "Default"),
                        ],
                        default="Not Informed",
                        max_length=255,
                    ),
                ),
                ("is_graduated", models.BooleanField(default=False, null=True)),
                ("main_graduation", models.CharField(max_length=128, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_infos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
