# Generated by Django 4.1.5 on 2023-01-12 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0002_alter_academic_educational_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="academic",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_infos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="academic",
            name="educational_level",
            field=models.CharField(
                choices=[
                    ("Early childhood education", "Isced0"),
                    ("Primary Education", "Isced1"),
                    ("Lower Secondary Education", "Isced2"),
                    ("Upper Secondary Education", "Isced3"),
                    ("Post-Secondary non-Tertiary Education", "Isced4"),
                    ("Short-cycle tertiary education", "Isced5"),
                    ("Bachelors degree or equivalent education level", "Isced6"),
                    ("Masters degree or equivalent education level", "Isced7"),
                    ("Doctoral degree or equivalent education level", "Isced8"),
                    ("Not Informed", "Default"),
                ],
                default="Not Informed",
                max_length=255,
            ),
        ),
    ]
