# Generated by Django 4.1.5 on 2023-01-12 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("work", "Work"),
                            ("sleep", "Sleep"),
                            ("study", "Study"),
                            ("hobby", "Hobby"),
                            ("health", "Health"),
                            ("commitment", "Default"),
                        ],
                        default="commitment",
                        max_length=16,
                    ),
                ),
                ("begans_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("description", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
