# Generated by Django 4.1.5 on 2023-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="type",
            field=models.CharField(
                choices=[
                    ("WORK", "Trabalho"),
                    ("SLEEP", "Dormindo"),
                    ("STUDY", "Estudo"),
                    ("HOBBY", "Hobby"),
                    ("HEALTH", "Saúde"),
                    ("COMMITMENT", "Compromisso"),
                ],
                default="COMMITMENT",
                max_length=16,
            ),
        ),
    ]
