# Generated by Django 4.1.5 on 2023-01-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="begans_at",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="ends_at",
            field=models.TimeField(),
        ),
    ]
